const user = {
	login: "mihir1729",
	id: 72518307,
	node_id: "MDQ6VXNlcjcyNTE4MzA3",
	avatar_url: "https://avatars.githubusercontent.com/u/72518307?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/mihir1729",
	html_url: "https://github.com/mihir1729",
	followers_url: "https://api.github.com/users/mihir1729/followers",
	following_url:
		"https://api.github.com/users/mihir1729/following{/other_user}",
	gists_url: "https://api.github.com/users/mihir1729/gists{/gist_id}",
	starred_url: "https://api.github.com/users/mihir1729/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/mihir1729/subscriptions",
	organizations_url: "https://api.github.com/users/mihir1729/orgs",
	repos_url: "https://api.github.com/users/mihir1729/repos",
	events_url: "https://api.github.com/users/mihir1729/events{/privacy}",
	received_events_url: "https://api.github.com/users/mihir1729/received_events",
	type: "User",
	site_admin: false,
	name: "Mihir Yadav",
	company: null,
	blog: "mihiryadav.com",
	location: "India",
	email: null,
	hireable: null,
	bio: "Self-Taught Developer",
	twitter_username: "mihhhir",
	public_repos: 30,
	public_gists: 0,
	followers: 1,
	following: 2,
	created_at: "2020-10-07T17:18:36Z",
	updated_at: "2022-10-12T18:55:09Z",
};

export default user;
